# Generated by Django 3.0.8 on 2020-07-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url1', models.CharField(max_length=500)),
                ('part1', models.CharField(choices=[('하체', '하체'), ('상체', '상체'), ('복근', '복근')], default='하체', max_length=2)),
                ('url2', models.CharField(max_length=500)),
                ('part2', models.CharField(choices=[('하체', '하체'), ('상체', '상체'), ('복근', '복근')], default='상체', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routinepage.Routine')),
            ],
        ),
    ]
